In [8]:
import numpy as np
import os
from tqdm import tqdm

In [9]:
non_mace_dir = r'D:\M143020071\raw_data_result\SKNA_signal\ch1\sr10000_500_2000_15s_ECG_signal_rpeak_5_10min_longer_v1_mr\non_mace_zscore/'
mace_dir = r'D:\M143020071\raw_data_result\SKNA_signal\ch1\sr10000_500_2000_15s_ECG_signal_rpeak_5_10min_longer_v1_mr\mace_zscore/'
save_non_mace_dir = r'D:\M143020071\raw_data_result\SKNA_signal\ch1\sr10000_500_2000_15s_ECG_signal_rpeak_5_10min_longer_1000pts_mr_9win\non_mace_zscore/'
save_mace_dir = r'D:\M143020071\raw_data_result\SKNA_signal\ch1\sr10000_500_2000_15s_ECG_signal_rpeak_5_10min_longer_1000pts_mr_9win\mace_zscore/'


In [10]:
for save_path in [save_non_mace_dir, save_mace_dir]:
    if not os.path.exists(save_path):
        os.makedirs(save_path)
        print(f'Created directory: {save_path}')
    else:
        print(f'Directory already exists: {save_path}')

Created directory: D:\M143020071\raw_data_result\SKNA_signal\ch1\sr10000_500_2000_15s_ECG_signal_rpeak_5_10min_longer_1000pts_mr_9win\non_mace_zscore/
Created directory: D:\M143020071\raw_data_result\SKNA_signal\ch1\sr10000_500_2000_15s_ECG_signal_rpeak_5_10min_longer_1000pts_mr_9win\mace_zscore/


In [ ]:
for data_dir, save_dir in zip([non_mace_dir, mace_dir], [save_non_mace_dir, save_mace_dir]):
    for filename in tqdm(os.listdir(data_dir),desc=f'Processing files in {os.path.basename(os.path.normpath(data_dir))}'):
        if filename.endswith('.npy'):
            try:
                raw_data = np.load(os.path.join(data_dir, filename))
                labels = raw_data[:, 0].astype(np.int32)
                signal = raw_data[:, 1:].astype(np.float32)
                signal_downsampled = signal.reshape(signal.shape[0], -1, 1000)
                mav_signal = np.mean(np.abs(signal_downsampled), axis=2)
                mav_signal = np.hstack((labels.reshape(-1, 1), mav_signal)).astype(np.float32)#變成了一個 20x1 的 2D 矩陣 (直欄向量) 為了hstack 維度要都是2維
                np.save(os.path.join(save_dir, filename), mav_signal[:9,:]) #取前n個特徵
            except Exception as e:
                print(f'Error processing file {filename}: {e}')
    print(f'Saved processed file: {save_dir}')
            

Processing files in non_mace_zscore: 100%|██████████| 432/432 [08:51<00:00,  1.23s/it]


Saved processed file: D:\M143020071\raw_data_result\SKNA_signal\ch1\sr10000_500_2000_15s_ECG_signal_rpeak_5_10min_longer_1000pts_mr_9win\non_mace_zscore/


Processing files in mace_zscore: 100%|██████████| 90/90 [02:15<00:00,  1.50s/it]

Saved processed file: D:\M143020071\raw_data_result\SKNA_signal\ch1\sr10000_500_2000_15s_ECG_signal_rpeak_5_10min_longer_1000pts_mr_9win\mace_zscore/


In [13]:
print(np.load(os.path.join(save_mace_dir, 'MACE021.npy')))
print(np.load(os.path.join(save_mace_dir, 'MACE021.npy')).shape)#原始長度：150,000 點(10000*15) 平均1000 =150
print(np.load(os.path.join(save_non_mace_dir, 'MACE001.npy')))
print(np.load(os.path.join(save_non_mace_dir, 'MACE001.npy')).shape)

[[1.         0.64160365 0.52072895 ... 0.7605604  0.5021969  0.49749714]
 [1.         0.5687057  0.4844951  ... 0.5437479  0.6378849  0.53290653]
 [1.         0.755573   0.724833   ... 0.54666734 0.68081963 0.80962116]
 ...
 [1.         0.964087   0.7669712  ... 0.6774494  0.61323965 0.69612104]
 [1.         1.3083177  1.1570024  ... 0.487081   0.45895085 0.5226112 ]
 [1.         1.4796689  1.3261211  ... 0.82396615 0.5355658  0.45175818]]
(9, 151)
[[0.         0.35634607 0.2547198  ... 0.8829098  0.7321964  0.571638  ]
 [0.         0.40886146 0.31321332 ... 0.8857089  0.69910884 0.7319823 ]
 [0.         0.9634535  0.9290912  ... 0.9586998  0.8859097  0.80486274]
 ...
 [0.         0.668119   0.6184632  ... 0.6839583  1.1656249  0.7883812 ]
 [0.         0.55930716 0.6090269  ... 0.92922986 0.9247991  0.58384395]
 [0.         0.6544695  0.5713377  ... 0.6641504  0.871522   0.81297326]]
(9, 151)
